export enum statusErrors {
    UNKNOWN = 0,
    PROPERTY_REQUIRED = 1,
    BD_ERROR = 2,
    USER_ALREADY_EXISTS = 3,
    TOKEN_NOT_FOUND = 4,
    TOKEN_IS_INVALID = 5,
    USER_NOT_FOUND = 6,
    ALREADY_EXISTS_BUSINESS_WITH_LEGAL_KEY = 7,
    ALREADY_EXISTS_BUSINESS_WITH_BUSINESS_KEY = 8,
    ALREADY_EXISTS_BUSINESS_FOR_USER = 9,
    OTP_INVALID_CODE = 10,
    OTP_EXPIRED_CODE = 11,
}
